### ISSUE TITLE
warning in TRAVIS: no DISPLAY variable so Tk is not available

### ISSUE THREAD

**Issue by Rasilgon** [COST-FP1304-PROFOUND/ProfoundData#1]
Original message:
> Found the following significant warnings:
>   Warning: no DISPLAY variable so Tk is not available

**Comment by florianhartig** [comment]
I think we need to start a X11 buffer, see 

- https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui
- https://github.com/travis-ci/travis-ci/issues/6987

which I have just tried in https://github.com/COST-FP1304-PROFOUND/ProfoundData/commit/e2aa177fcd451ae6e99a5e399fe8bed0cdd28917

but I wonder why - apparently, somewhere in the help / vignette / tests, there is a call that needs that. My preference would be to remove this call, or at least identify what creates the problems so that we can decide whether this is an essential line of code

**Comment by florianhartig** [comment]
OK, with the changes I made to the .yml, this builds now. 

I'm leaving this open to decide if we actually need these X11 calls / graphics calls or whatever caused the issue in the first place.

**Comment by Rasilgon** [comment]
Ok, great that it works. Actually I tried that in https://github.com/COST-FP1304-PROFOUND/ProfoundData/commit/fd71eb04814e24ad2f37a8b1d80a70859e816dd4 and it did not work. I think the the line `cd ProfoundData` was placed some where else in my commit. 
Anyway, this is now solved. Thanks!
