### ISSUE TITLE
Check if database exist

### ISSUE THREAD

**Issue by florianhartig** [COST-FP1304-PROFOUND/ProfoundData#15]
All functions should check if db exist, and if not, call setDB  rather than throwing errors. This will direct the user directly to the necessary steps.

**Comment by Rasilgon** [comment]
Currently the functions check if db exist, by trying to connect to it and return an error message. The code is below.  

`  conn <- try(makeConnection(), T)
  if ('try-error' %in% class(conn)){
    stop("Invalid database connection")
  }else{
    RSQLite::dbDisconnect(conn)
  }`

The idea would be to change the error message to something point to setDB, right? 
Instead of "Invalid database connection", the warning could be  "Please first use setDB to connect to a valid DB". It is what you were thinking of?

**Comment by florianhartig** [comment]
yes, exactly - is this particular check really always called? I thought I received an even more cryptic error message, but not sure

**Comment by Rasilgon** [comment]
OK, great.  Then I am changing the message.

In getData, plotData and summarizeData is done when calling parseQuery, which has the above code lines. The remaining functions (short-simple functions) have the check included.

I will go through the errors calls. It is not good if they sound cryptic.

**Comment by florianhartig** [comment]
OK ... if you do this, maybe better to outsorce this call into a helper function? (easier to maintain)

**Comment by florianhartig** [comment]
Hi Ramiro, this is not done, is it?

**Comment by Rasilgon** [comment]
Still have to check it and commit it. Probably done by the end of week(end)

**Comment by matsmahnken** [comment]
After talking to @Rasilgon we decided to simply change the message text in every related message from "Invalid database connection" to "Invalid database connection. Please use setDB() to connect to a valid DB" (see #24). This is the simplest fix for now.
This means the error call is not outscored. If we want to do this in the future, we need to keep it in mind.

Does this solve the issue for now @florianhartig?

**Comment by florianhartig** [comment]
OK, I have merged this for now, but technically, I don't think this is very clean. As it is, we now have various places in the code where we do the same thing, i.e
 
```
  conn <- try(makeConnection(), T)
  if ('try-error' %in% class(conn)){
    stop("Invalid database connection", call. = FALSE)
    stop("Invalid database connection. Please use setDB() to connect to a valid DB", call. = FALSE)
  }
```
My main point is that we should have a check db function, that is called in any function that requires a db. This check function could have this piece of code, but could also do something else, e.g. setDB

**Comment by matsmahnken** [comment]
I agree that it is not very clean.
There is actually the `makeConnection()` function that does a test for a valid DB connection besides testing if needed packages are loaded. Maybe that could be used. `makeConnection()` is already used in many (if not all) of the connection tests.
@Rasilgon mentioned that there was a reason to use `makeConnection()` but then wrap it with `try()` instead of putting all the testing and messaging in the function itself.

**Comment by florianhartig** [comment]
I don't see why we couldn't put the try also in the makeConnection(). In the worst case, we could do a subfunction, but should be good to have the function argument in {}

**Comment by matsmahnken** [comment]
You are right. I am trying to include this but my main problem is that `dbConnect()` does not produce an error if I give a name/path for a DB that does not exist. This would be a prerequesite for the `makeConnection()` function to work, right?

`dbConnect(RSQLite::SQLite(), "non-existent-file")` for example does not give an error as I would expect. What am I missing here?

**Comment by matsmahnken** [comment]
In the meantime I found that it works if `dbConnection()` has a default `dbname=NA`. I don't know if this affects some other parts of the code but for me it works well for calling `setDB()` from `makeConnection()` if there is no valid DB connection.
See linked pull request #25
