### ISSUE TITLE
Package size

### ISSUE THREAD

**Issue by florianhartig** [COST-FP1304-PROFOUND/ProfoundData#2]
Travis warning 

```
 installed size is 16.6Mb
  sub-directories of 1Mb or more:
    doc  16.4Mbchecking top-level files ... NOTE
```

@Rasilgon - for what do we need so much data in the package?

**Comment by Rasilgon** [comment]
There was originally a very long vignette with

- the database structure
- a summary of the data in the DB
- package usage explanation 

Now I distributed this information in 3 vignettes, one for each purpose

- the database structure (PROFOUNDdatabase.html) 0.556 MB
- a summary of the data in the DB (PROFOUNDsites.html) 14.9 MB
- package usage explanation  (ProfoundData.html) 1.3 MB

Perhaps we move the vignette PROFOUNDsites.html out of the package.

**Comment by florianhartig** [comment]
btw., this is probably also because of the html files in the vignette folder

**Comment by Rasilgon** [comment]
yes,  exactly. The html files in the vignette folder have the 3 static vignettes, already built (https://cran.r-project.org/web/packages/R.rsp/vignettes/R_packages-Static_PDF_and_HTML_vignettes.pdf) because they depend on the connection to the DB.

**Comment by florianhartig** [comment]
Ah, OK ... hm ... I wonder if this is a good long-term solution.

If we submit to CRAN, vignettes are build anyway ... normal vignettes would only be built for the test, I wonder if it would not be better to suppress their built in the CRAN tests?

Our Repo will blow up like hell if we commit 15MB with every version of the package

**Comment by florianhartig** [comment]
Also, I just noted that the vignette folder only contains the html files, where are the Rmd files?

**Comment by florianhartig** [comment]
Ah, I think I just found them in data-raw - is this the ideal place?

**Comment by Rasilgon** [comment]
I think that there are two issues here


1. The  static vignettes
2. The size of the vignettes

*1. Static vignettes*
I created static (pre-built) vignettes because the connection to the database is needed to build them.  In the vignettes folder I put the html vignette and the html.asis file, which has the instructions to "build " the static vignette. 
The Rmd files should not be compiled because they will raise an error since the connection to the DB is needed. However, it is good practice to provide the code that create the vignettes. So, I thought to put the Rmd files in data-raw because it is the place to put code related to the package but not meant to be run (http://r-pkgs.had.co.nz/data.html)

*2.  Size of the vignettes*
I think we can remove the vignette that weights 14.9 MB (PROFOUNDsites.html). I could include a function in the package to create this report once the user has set the connection to the DB.

**Comment by christopherreyer** [comment]
just and addition: the vignettes should also be linkned on the doi-lanidng page, so also people who are not usingt he r-package can access them.
