### ISSUE TITLE
Travis builds are really long

### ISSUE THREAD

**Issue by florianhartig** [COST-FP1304-PROFOUND/ProfoundData#5]
I see our last builds are taking ages, e.g. 1 hr 27 min 41 sec - what are we doing in the builds that is taking so much time? Shouldn't this just be a few plots etc?

**Comment by Rasilgon** [comment]
I think that it might take long because I included calls to install the nectcdf libraries (netcdf and udunits), besides tcl and tk. Our function writeNetCDF depends on RNetCDF which requires the netcdf libraries.

The vignettes are already build (static html) and the tests are not run in travis, and thus they should not take time, right?

**Comment by florianhartig** [comment]
No, vignettes and help files will be newly built during the checks - does it take long to build the vignette?

Not sure why installing the nectcdf would take hours?

**Comment by Rasilgon** [comment]
After my last commit. builds only took circa 3 min.

**Comment by florianhartig** [comment]
yes, seems that this is solved, no idea why it was so slow before
